version: '3.3'

services:
  jupyter:
    image: lobr266238/jupyterhub-basic
    container_name: JupyterHub
    volumes: 
       - etc:/etc/
       - user:/home/
    ports:
      - "8000:8000"

volumes:
  etc:
  user:
