version: '3.3'

services:
  jupyter:
    image: lobr266238/jupyterhub-basic
    container_name: JupyterHub
    volumes: 
       - etc:/etc/
       - users:/home/
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  etc:
  users:
